### ISSUE TITLE
AutorecoveringChannel doesn't recover when waitForConfirmsOrDie() throws TimeoutException from waitForConfirms(ChannelN.java:204)

### ISSUE THREAD

**Issue by XandelSA** [rabbitmq/rabbitmq-java-client#151]
Application details:

Java 1.6
AMQP-Client: 3.6.1

Issue:

I have noticed that the when using publisher confirms and waiting for confirmation with `waitForConfirmsOrDie(timeout)`, a `TimeoutException` gets thrown from one of two locations; `com.rabbitmq.client.impl.ChannelN.waitForConfirms(ChannelN.java:204)` or at `com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)`.

The former (`ChannelN.waitForConfirms()`) causes the channel to never recover while the latter (`BlockingCell.get()`) works as expected - the channel recovers once the network becomes stable again.

Here are the complete two different stacktraces in my scenario:

Unrecoverable:
```
java.util.concurrent.TimeoutException
	at com.rabbitmq.client.impl.ChannelN.waitForConfirms(ChannelN.java:204)
	at com.rabbitmq.client.impl.ChannelN.waitForConfirmsOrDie(ChannelN.java:225)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.waitForConfirmsOrDie(AutorecoveringChannel.java:438)
	at my.app.processor.MessageSender$2.run(MessageSender.java:117)
	at java.lang.Thread.run(Unknown Source)
```

Recoverable:
```
java.util.concurrent.TimeoutException
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:111)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:37)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:367)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:582)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:509)
	at com.rabbitmq.client.impl.ChannelN.waitForConfirmsOrDie(ChannelN.java:230)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.waitForConfirmsOrDie(AutorecoveringChannel.java:438)
	at my.app.processor.MessageSender$2.run(MessageSender.java:117)
	at java.lang.Thread.run(Unknown Source)
```

Some extra information:

- Both exceptions are thrown from the exact same `waitForConfirmsOrDie(timeout)` call.
- The network is unfortunately very unstable (2G) and drops often. Recreating this scenario in a test environment is almost impossible.
- If I encounter a `TimeoutException` while trying to `basicPublish` I wait for the channel to open by intermittently checking `channel.isOpen()` before attempting any further `basicPublish()` calls.

Please let me know if you require any more information.

**Comment by michaelklishin** [comment]
Connection recovery *cannot* recover application code, which is where confirm timeouts happen. You need to handle undelivered confirms yourself. In addition, currently connection recovery only recovers topology and intentionally doesn't try to re-publish messages, which is mentioned in the docs.

**Comment by michaelklishin** [comment]
`ChannelN` instances are re-created by `AutorecoveringChannel` during recovery, so I can't see how an application thread that is waiting on a `ChannelN` instance can affect recovery. A more likely issue is that since publishing a message when connection is down throws an exception, your channel ends up being closed at a different moment in time.

Recovery Java, .NET, and Ruby (Bunny) clients does not cover this well. In a recently developed Objective-C client outgoing messages are enqueued by the client internally before being sent (the "queue" here is an in memory data structure and has nothing with RabbitMQ queues, of course).

**Comment by XandelSA** [comment]
May I then ask - with Autorecovering channels - when it is safe to open a new channel to correct the issue? How should the existing one be handled to avoid it "recovering later" if that's possible?

**Comment by XandelSA** [comment]
> A more likely issue is that since publishing a message when connection is down throws an exception, your channel ends up being closed at a different moment in time.

Should it not then still recover?

**Comment by michaelklishin** [comment]
Automatic recovery only covers TCP connectivity issues and server-sent `connection.close`. It does not try to recover channels that were closed due to a channel exception or an application-level exception, by design.

Given that a connection had recovered and you do not end up leaking or opening hundreds or thousands of channels per connection, opening new channels is perfectly fine.

**Comment by XandelSA** [comment]
Alright, thank you for your help. I was under the impression that the channel recovered itself independently of its connection. 

So to confirm - once a channel has been closed (either by calling `channel.close()` or after encountering an `com.rabbitmq.client.AlreadyClosedException` it is safe to request a new channel from the connection?

**Comment by michaelklishin** [comment]
Channels are recovered after their connection finishes recovering. Yes, it should be perfectly fine to open a new channel.
