### ISSUE TITLE
Handling reply codes manually is unergonomic

### ISSUE THREAD

**Issue by michaelsproul** [rabbitmq/rabbitmq-java-client#206]
It would be nice if the library provided an enum for the possible values of `replyCode` that can be sent during a `basic.return`. It would also be good if the enum could be converted to a human-readable string for error messages.

I'd like to be able to do this:

```java
void handleBasicReturn(ReplyCode replyCode, ...) {
   logger.warn("Message returned with code: {}, reason: {}", replyCode, replyCode.description());
   // .. handle the failure ..
}
```

List of reply codes here: https://www.rabbitmq.com/amqp-0-9-1-reference.html#constants

**Comment by michaelklishin** [comment]
Messages are returned when they cannot be routed. What difference does it make for the publisher if it's because the exchange does not exist?

I'm afraid you misunderstood how channel errors and returns work since most of the time there is no connection between them.

Please start a conversation about this on rabbitmq-users first so that your idea can be hashed out. Thanks.

**Comment by michaelklishin** [comment]
Also, channel errors are supposed to be handled using shutdown handlers which does have access to the code and error message.

**Comment by michaelsproul** [comment]
I think you're mistaken about what I was requesting, but don't worry, the existing `replyText` and `replyCode` parameters on `ReturnListener::handleReturn` are good enough (I was originally just suggesting an enum rather than the bare int).

Method signature for reference: http://www.rabbitmq.com/releases/rabbitmq-java-client/v3.6.5/rabbitmq-java-client-javadoc-3.6.5/com/rabbitmq/client/ReturnListener.html

Thanks for the quick response 👍

**Comment by michaelklishin** [comment]
Thanks for clarifying. Switching to an enum would be a breaking change :(
