### ISSUE TITLE
Add callback-based method in Channel

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-java-client#215]
E.g. in `Channel`:
```java
void asyncRpc(Method method, CommandCallback callback) throws IOException;
```

With:
```java
public interface CommandCallback {
	void handle(Command response);
}
```

This could allow to build a reactive API and also, combined with NIO, to have a truly non-blocking client (right now RPC calls are serialized, at least at the channel level).

**Comment by michaelklishin** [comment]
I suspect we then want an entire new `ChannelN` implementation.

**Comment by michaelklishin** [comment]
…and perhaps an interface, e.g. `AsyncChannel`. I'd also consider using futures over callbacks (or at least both).

**Comment by acogoluegnes** [comment]
We may not have to rewrite `ChannelN` from scratch, I hope we can change the [outstanding RPC call property](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/AMQChannel.java#L57) in favor of a queue and support the callback scenario.
The point here is to have a foundation for reactive and opinionated extensions to build on (they tend to prefer callback over futures usually).
The `AsyncChannel` scenario would be something else, more involving I guess.
I'll try to start experimenting in the next days/weeks.

**Comment by smaldini** [comment]
Yes please no Future or it would be CompletableFuture if the java version supports it. Even so, the problem is more than we need to have the basic abilities to : 
- trigger async work on demand (call method)
- not blocking on that async method at all, Future#get would only encourage that, kafka mixed up these two API styles.
- getting the status in the callback : success(result)/error(cause)  or getting 2 callbacks for success/error
- inspired from https://github.com/reactive-streams/reactive-streams-jvm even tho its not implementing it. For instance success/error should be unique and terminal, definition of "blocking operations"

**Comment by michaelklishin** [comment]
I have no problem with rolling with `CompletableFuture` and requiring JDK 8 now that we are no longer tied to RabbitMQ releases and thus can bump version numbers at will.
