### ISSUE TITLE
Expose replyText from reason of ShutdownSignalException

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-java-client#254]
ShutdownSignalException::getReason() -- whichever class that is -- has replyText but I can't get it. I have to call toString() and parse it out, which is error prone. Would it be possible to please expose replyText?

**Comment by michaelklishin** [comment]
`ShutdownSignalException#getReason` returns a `com.rabbitmq.client.Method` which cannot have `getReplyText` because not all methods have that field.

Specific methods that have it, e.g. `com.rabbitmq.client.AMQP.Connection.Close`, expose it, e.g. `Connection.Close` has `getReplyText`. So you need to cast or switch on the returned value type.
