### ISSUE TITLE
Changelog for 4.1.0

### ISSUE THREAD

**Issue by vibhuyadav** [rabbitmq/rabbitmq-java-client#255]
I cannot find the official changelog for 4.1.0 client. Is there one I cannot find? If not, can one be created?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Have you seen [this repo's releases page](https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v4.1.0)?

**Comment by vibhuyadav** [comment]
Thank you so much. Don’t know how i missed it. Do you have a RSS feed I can subscribe to so that I don’t miss any updates?

**Comment by michaelklishin** [comment]
This client uses GitHub releases for release notes. I'm not sure if it provides an RSS or Atom feed. I believe there are services that provide notifications for any Maven artifact updates but I cannot name one right away.

**Comment by vibhuyadav** [comment]
Configured an atom feed. Thanks! :)
