### ISSUE TITLE
TopologyRecoveryException when the channel has been closed

### ISSUE THREAD

**Issue by a14n** [rabbitmq/rabbitmq-java-client#266]
With _com.rabbitmq::amqp-client::4.1.0_ the following program doesn't manage to recover its topology (only one queue declared on a closed channel when the rabbitmq server restarts)

```java
public static void main(String[] args) throws IOException, TimeoutException {
    final ConnectionFactory factory = new ConnectionFactory();
    final Connection connection = factory.newConnection();

    final Channel channel1 = connection.createChannel();
    channel1.queueDeclare("queue", false, false, false, null);
    channel1.close();

    final Channel channel2 = connection.createChannel();
    channel2.basicQos(1, false);
    channel2.basicConsume("queue", new DefaultConsumer(channel2));
}
```

If I comment out the line `channel1.close();` the exception isn't thrown but there's a channel leak.

Why doesn't the topology recovery be done in a brand new channel ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions fofor potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
@a14n see https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/320. You expect topology recovery to imitate durable entities, which is NOT why it exists. Explicitly closed channels intentionally invalidate all the cached entities that were declared on them: that part of the topology is considered to be done with. If you need such queues and so on to stick around, declare them as durable.

**Comment by michaelklishin** [comment]
You claim that there is a channel leak but provide no evidence. I don't see how there can be a channel leak given that connection recovery will "reopen" all `AutorecoveringChannel` instances by opening a new channel on the brand new recovered connection and the channels on the old connection won't have any references to them.

When a connection is closed, all channels on it are closed as far as RabbitMQ is concerned. Whether they are "reopened" by a client recovery feature at a later point is unknown to the broker. It sees any "reopened" channel as a new channel on a new connection.

This is mailing list material. Please provide evidence if you are sure there is a channel leak.

**Comment by a14n** [comment]
Thanks for your answer.

Sorry for not having been really clear. By _channel leak_ I meant that my application need to maintain the channel open (when a topology operation is done on it) to work as I expected and to avoid the _TopologyRecoveryException_.

I didn't consider using durable channel but reading rabbitmq/rabbitmq-dotnet-client#320 it looks like I had the same expectations as its author.

>Explicitly closed channels intentionally invalidate all the cached entities that were declared on them: that part of the topology is considered to be done with.

I didn't see _channel_ lifecycle this way. You should consider to document this somewhere (perhaps in [channels](https://www.rabbitmq.com/tutorials/amqp-concepts.html#amqp-channels) )

Thanks again for your time.

**Comment by michaelklishin** [comment]
We can certainly clarify some of this in various recovery guides. The protocol overview document is meant for complete beginners and be short. Connection and topology recovery is a client library implementation detail.
