### ISSUE TITLE
spurious shutdown signal when topologyRecovery=true

### ISSUE THREAD

**Issue by chsava** [rabbitmq/rabbitmq-java-client#267]
We have tried enabling topologyRecovery=true in our code, hoping it will help us automatically recover rabbit queues when tcp connections are experiencing problems. What seems to happen is that queues are indeed recovered, but a spurious shutdown signal is being generated which triggers a response from our higher level connection-recovery code.

I think the shutdown signal should not be generated in case queue is successfully recovered.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions fofor potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Shutdown signals will be dispatched when a connection goes down regardless of whether connection recovery is used. Automatic connection recovery uses a shutdown listener in order to know when to kick in.

So this is expected.

**Comment by chsava** [comment]
Then how can we distinguish between "real" shutdown when topology recovery failed to do its job and "spurious" signals when topology recovery has successfully recovered the queue and therefore no higher-level intervention is needed?

**Comment by michaelklishin** [comment]
@chsava if you need a "divine intervention" then perhaps you shouldn't use automatic connection recovery and recover your own code. It was never intended to cover 100% of the cases.

Shutdown signal events carry a reason field which lets you do some filtering (such as explicit connection shutdown initiated by the app). You can use passive declares or declare entities as durable to make sure that key topology elements that are essential to your app are there after recovery.

**Comment by chsava** [comment]
Even if I understand the automatic topology recovery will not completely obviate the need for higher-level connection recovery code, I do expect such higher level connection recovery code will need to run less often as when not using topology recovery at all. However, I am seeing the shutdown signals are always generated etc. I think this expectancy is a very realistic one: we do expect the boss to be less busy when the subordinates do their job well, right?..

**Comment by chsava** [comment]
..and if the boss is just as busy, then either the subordinates are failing in their job, or the communication protocol is not right.

**Comment by michaelklishin** [comment]
@chsava automatic connection recovery was introduced years after the shutdown protocol. The former relies on the latter, does not replace it and does not intend to change its behaviour. If you have to "react" to shutdown events then perhaps you need to switch to "manual recovery" to begin with.

Sorry but your analogy is not as witty as you think it is.

**Comment by michaelklishin** [comment]
It is also perfectly reasonable to argue that even with automatic connection recovery in place, connection failure events (which is a large part of what the shutdown protocol covers) should still be emitted. If a vehicle is fixed after an accident, does it mean that the accident should never be recorded? Yeah, let's cut it with the analogies nonsense.
