### ISSUE TITLE
Channel Thread safety

### ISSUE THREAD

**Issue by stepan-romankov** [rabbitmq/rabbitmq-java-client#268]
There is hard to understand from official java api guide https://www.rabbitmq.com/api-guide.html#channel-threads that Publisher Confirms shouldn't be used in handleDelivery method of Consumer. The issue is that by default Consumer are executed in multiple threads (default or shared connection thread pool) and handleDelivery method can be executed in multiple threads simultaneously, receiving the same channel instance. When we try to call Channel#basicPublish on this channel instance in combination with Publisher Confirms concurrency issue can happen with ChannelN#nextPublishSeqNo. Namely both calls to Channel#getNextPublishSeqNo will return the same SeqNo. 

This is very hard to understand from documentation if you haven't deeply looked inside source code or java-client.

**Comment by michaelklishin** [comment]
From [the docs](http://www.rabbitmq.com/api-guide.html):

```
Channel instances must not be shared between threads. Applications should prefer using a Channel per thread instead of sharing the same Channel across multiple threads. While some operations on channels are safe to invoke concurrently, some are not and will result in incorrect frame interleaving on the wire.
```

I will try to clarify this but I do not consider this part to be undocumented or that difficult to find. Ditto for mailing list threads with the same question.

**Comment by michaelklishin** [comment]
To clarify: the above note applies to all publishing, regardless of whether publisher confirms are used. Publishing on a [shared channel is a no-no](https://groups.google.com/d/msg/rabbitmq-users/gfm1iYMlw-Q/kPG22wgaDAAJ).

**Comment by stepan-romankov** [comment]
You are right, but I'm about scenario when you just try to publishMessage just from inside handleDelivery method. So that rabbitmq client already creates a situation where channel is shared between threads.

Another piece of documentation also makes this confusion:

> Callbacks to Consumers are dispatched on a thread separate from the thread managed by the Connection. This means that  Consumers can safely call blocking methods on the  Connection or Channel, such as  queueDeclare, txCommit,  basicCancel or basicPublish.

**Comment by michaelklishin** [comment]
@stepan-romankov hm, that sentence is wrong on multiple levels, e.g. `basic.publish` is not a synchronous method (there is no response frame in the protocol for it). I'm trying to clarify it as we speak.

In general, publishing from `Consumer#handleDelivery` is a lot more nuanced. Consumer method dispatch implementation uses a "work pool" which does guarantee ordered processing *per channel*. In practice that means that publishing from the aforementioned method works very well (of all concurrency hazards that we see this client users run into, this is not at all common). It is also possible to provide a custom `j.u.c.ExecutorService` when instantiating a connection and avoid concurrent consumer dispatch entirely.

Unfortunately dumping the details of how consumer dispatch works is not only forward-compatible, it will make the section more confusing to those without a lot of concurrent programming experience :/

**Comment by stepan-romankov** [comment]
@michaelklishin 
> "work pool" which does guarantee ordered processing per channel
By default work pool instantiates ConsumerWorkService#DEFAULT_NUM_THREADS threads, which process messages in parallel. So only the order of how messages will be submitted to ExecutorService is guaranteed and for the default behaviour multiple messages can be processed in parallel. I think this should be clarified in documentation somehow:
> Don't publish messages from channel received in handleDelivery as parameter, unless you understand what you do :)

**Comment by michaelklishin** [comment]
@stepan-romankov we are not going to use such blanket statements in our concurrency related docs since the devil is always in the details when it comes to concurrency hazards but I will try to get your message home one way or another :)

**Comment by michaelklishin** [comment]
It's worth clarifying what the statement quoted above about "synchronous method safety" actually tries to say.

A long time ago, before consumer operations were dispatched using a thread pool they were dispatched on the I/O thread ("the main loop"). This side steps a lot of concurrency hazards ;) but has a couple of very obvious issues: long running consumer operations block the loop and therefore no frames coming from RabbitMQ can be processed.

Specifically if a consumer invoked an operation that expects a response, such as `Channel#queueDeclare`, that would result in a deadlock: the method cannot return until a response has arrived but it will never do because the caller has blocked the I/O loop.

After `ConsumerWorkService` and friends were introduced, the docs were updated to mention that it is now safe to use synchronous operations from consumer callbacks. Unfortunately it somehow
included `basic.publish` to the list of methods, even though it never waits for a response (there is no response in the protocol).

The sentence above does not try to tell the reader that it is absolutely safe to do anything from consumer callbacks: very often it depends on application semantics and libraries cannot protect
the user from herself. But I can see how it could lead some readers to believe just that. So thank you for reporting this, I'm about to push a fairly substantial update to the relevant areas of the Java client guide.

**Comment by stepan-romankov** [comment]
@michaelklishin  Thanks for the detailed reply!

**Comment by michaelklishin** [comment]
@stepan-romankov the updated version is already up on http://www.rabbitmq.com/api-guide.html. Let me know if you find it clearer. Feel free to file new issues for https://github.com/rabbitmq/rabbitmq-website in case you have specific suggestions (or submit pull requests).

**Comment by stepan-romankov** [comment]
@michaelklishin 

> Consuming in one thread and publishing in another thread on a shared channel can be safe.

This phrase might really avoid a lot of mistakes by newbies.

**Comment by salvois** [comment]
Hello,
sorry for resurrecting this issue, but I have a doubt on how reliable publishing is even when not sharing a Channel/Model between threads.

Both the Java and the .net client libraries increment nextPublishSeqNo early before actually trying to send anything on the wire. If an exception is thrown while sending, wouldn't that make the sequence number of the client and that of server inconsistent?

E.g. client sends one message, client seq=1, server seq=1; client sends another message, client seq=2, but exception is thrown before the server even knows, server seq still=1; client sends a third message, client seq=3, server seq=2; client sends a fourth message, client seq=4, server seq=3, client receives publisher confirm for seq=3 but it really was for 4 as far as the client believes.

Thank you and sorry if I missed something,
   Salvo

**Comment by michaelklishin** [comment]
This belongs to the mailing list.
