### ISSUE TITLE
RabbitMQ flooded by new connections

### ISSUE THREAD

**Issue by Allan-Nava** [rabbitmq/rabbitmq-java-client#287]
Hi,

i'm using java api client with Automatic Recovery but every time it loses the connection, when it reconnects it creates a new connection on a different port, flooding my RabbitMQ with multiple connections.The environment I am working on loses the connection frequently.

Is it possibile use the same connection when it tries to reconnect?

Thanks in advance

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Every AMQP 0-9-1 connection (Java client connection) uses a TCP connection. Every time a connection is "lost" (goes down, heartbeat timeout is reached, and so on), a new TCP connection has to be opened. There is no way to "reuse" the TCP connection you had before.

I'm guessing but your question probably comes down to two things:

 * How to make gone connections to be "cleared" on the server end quicker. See [Heartbeats](http://www.rabbitmq.com/heartbeats.html).
 * How to tune node file descriptor limit and/or make each connection use less memory by decreasing TCP buffer size. See [Networking](http://www.rabbitmq.com/networking.html).
 * How to make a node accept larger bursts of concurrent inbound TCP connections e.g. when a lot of clients lose connections around the same time. Also covered in the Networking guide.

With those 4 things addressed via configuration even frequent reconnections should not be problematic. If they are, perhaps your applications use connections in a suboptimal way (can use fewer of them to achieve the same thing).

**Comment by Allan-Nava** [comment]
Hi,

I used Lyra library but when the client lost connection, it still create a
new connections like attached picture.
I need to clear the closed old connections.

This is my subiscribe method:

private void subscribe(final Handler handler)
{
    subscribeThread = new Thread(new Runnable() {
        @Override
        public void run() {
            while(true) {
                try {
                    //connection = connectionFactory.newConnection();
                    connection =
MySingletonConnection.getInstance().getConnection();
                    //connection = Connections.create(options, config);
                    Channel channel = connection.createChannel();
                    // Declare a queue and bind it to an exchange.
                    com.rabbitmq.client.AMQP.Queue.DeclareOk q =
channel.queueDeclare("manager2box-"+ROUTING_KEY, true, false, true,
null);
                    channel.queueBind(q.getQueue(), EXCHANGE, ROUTING_KEY);
                    // Create the QueueingConsumer and have it consume
from the queue
                    QueueingConsumer consumer = new QueueingConsumer(channel);
                    channel.basicConsume(q.getQueue(), false, consumer);

                    while (true) {
                        QueueingConsumer.Delivery delivery =
consumer.nextDelivery();
                        String message = new String(delivery.getBody());
                        Log.d(TAG, message);
                        Message msg = handler.obtainMessage();
                        Bundle bundle = new Bundle();
                        bundle.putString("commandBundle", message);
                        msg.setData(bundle);
                        handler.sendMessage(msg);
                    }
                } catch (InterruptedException e) {
                    Log.d(TAG, "InterruptedException");
                    e.printStackTrace();
                    break;
                } catch (Exception e1) {
                    Log.d(TAG, "Connection broken: " + e1.getClass().getName());
                    e1.printStackTrace();
                    try {
                        Thread.sleep(5000); //sleep and then try again
                    } catch (InterruptedException e) {
                        Log.d(TAG, "InterruptedException");
                        e.printStackTrace();
                        break;
                    }
                }
            }
        }
    });
    subscribeThread.start();
}


This is my SingletonConnection:

public class MySingletonConnection{
    public static final MySingletonConnection INSTANCE = new
MySingletonConnection();
    private static Connection connection;

    private final String TAG = "MySingletonConnection";
    private final String EXCHANGE    = "manager2box";
    private final String USERNAME    = "manager";
    private final String PASSWORD    = "MGXxXq72HscXzakR";
    //private final String HOST        = "192.168.1.147";
    private final String HOST        = "portal.seafy.me";
    private final String ROUTING_KEY = Utils.getIPAddress();
    private Config config;
    private ConnectionOptions options;

    private MySingletonConnection(){
        //Lyra config
        config = new Config()
                .withConnectionListeners()
                .withRecoveryPolicy(RecoveryPolicies.recoverAlways())
                .withRetryPolicy(new RetryPolicy()
                        .withMaxAttempts(20)
                        .withInterval(Duration.seconds(5))
                        .withMaxDuration(Duration.minutes(5)));
        //Lyra option config for connection
        options = new ConnectionOptions().withUsername(USERNAME)
                .withRequestedHeartbeat(Duration.seconds(30))
                .withPassword(PASSWORD)
                .withHost(HOST)
                .withPort(5672);
        try {
            connection = Connections.create(options, config);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (TimeoutException e) {
            e.printStackTrace();
        }
    }

    public static MySingletonConnection getInstance(){
        return INSTANCE;
    }

    public Connection getConnection( ) {
        return connection;
    }
}


2017-07-03 14:41 GMT+02:00 Michael Klishin <notifications@github.com>:

**Comment by michaelklishin** [comment]
@Allan-Nava your code opens connections in a `while(true)` loop. That alone should create a very high rate of connections. On top of that, this client and Lyra both will perform connection recovery by default.

I recommended two doc guides that demonstrate settings that will make connection cleanup on the server end to happen quicker. On the client end, if a connection is lost (there is an I/O exception), it is considered to be closed virtually immediately by both this client and Lyra.

I'd start by making your code not use `while(true)`, in particular for opening connections and channels, and then see if you really see any "dangling connections. If you do, post `netstat` or similar output and server logs to rabbitmq-users as our team does not use GitHub issue for investigations and discussions.

**Comment by michaelklishin** [comment]
Moreover, not using `QueueingConsumer` — which has been long deprecated — will let you avoid using `while(true)` entirely. See how [Java client tutorials](http://www.rabbitmq.com/getstarted.html) consume messages: there are no `while` loops.

**Comment by Allan-Nava** [comment]
This is where I found the lines of code I'm using: [link](https://github.com/cloudamqp/android-example/blob/master/cloudAMQP/src/com/cloudamqp/androidexample/ActivityHome.java#L95).

However I think I need the loop because in my application is fundamental that the client is always connected and as fast as possible.

Is there a better and reliable way to do it without the loop? I can understand it's wrong to use it.
Thanks, Allan

**Comment by michaelklishin** [comment]
@Allan-Nava you don't need a loop, even if your client is "always connected" (which is not realistic, as you will learn over time: that's why this client and Lyra have recovery features *and* delays between recovery retries) and "as fast as possible" (`QueueingConsumer` is not inherently any faster than any other `Consumer` implementation).

Your code floods your system with connections and you expect this client and Lyra to somehow fix that. They won't. You are doing it wrong.

I forgot to mention, `QueueingConsumer` is not supported by automatic connection recovery.

**Comment by Allan-Nava** [comment]
@michaelklishin Ok, i used the [example](https://github.com/cloudamqp/android-example/blob/master/cloudAMQP/src/com/cloudamqp/androidexample/ActivityHome.java#L107).

How can i fix the QueueingConsumer ? 

Thanks, Allan

**Comment by michaelklishin** [comment]
@Allan-Nava consider going through [RabbitMQ tutorials](http://www.rabbitmq.com/getstarted.html), most of them use a `Consumer` implementation that's not `QueueingConsumer`.
