### ISSUE TITLE
Invalid stream header: 61736466 when trying to read message published in management interface

### ISSUE THREAD

**Issue by benze** [rabbitmq/rabbitmq-java-client#296]
I'm trying to do a quick test with Spring, RabbitMQ and RabbitMQ JMS.  I have configured my application with:

- Spring Boot 1.5.6
- RabbitMQ-jms 1.7.0
- RabbitMQ amqp-client 4.2.0

When I listen for a message in RabbitMQ, and publish it via the Management Interface, I get a StreamCorruptedException : invalid stream header: 61736466  thrown.

Digging through the code, I see this is thrown by the call in WhiteListObjectInputStream().super().  In the java.io.ObjectInputStream() constructor, it checks the stream header for the STREAM_MAGIC & STREAM_VERSION.

Is this because it was a non-Java library (ie: the management interface) that created the message?  Is there a problem with the way I created the connection?  Is there an issue with the amqp library?

```
    @Bean
    public DefaultJmsListenerContainerFactory jmsListenerContainerFactory() {
        DefaultJmsListenerContainerFactory factory =
                new DefaultJmsListenerContainerFactory();
        RMQConnectionFactory conn = new RMQConnectionFactory();
        conn.setUsername("test");
        conn.setPassword("test");
        conn.setHost("localhost");
        conn.setPort(5672);
        conn.setVirtualHost("test");
        factory.setConnectionFactory(conn);
        factory.setDestinationResolver(new DynamicDestinationResolver() );
        factory.setConcurrency("3-10");
        return factory;
    }
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
JMS client assumes it interoperates with either JMS client or (with certain restrictions) RabbitMQ Java client. Management UI publishing form sets an absolute minimum of message properties by default.
