### ISSUE TITLE
Unrecognized Windows Sockets error: 0: recv failed

### ISSUE THREAD

**Issue by DavidSoong128** [rabbitmq/rabbitmq-java-client#332]
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_73]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_73]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_73]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_73]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_73]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_73]
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[na:1.8.0_73]
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95) ~[amqp-client-3.6.2.jar:na]
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139) [amqp-client-3.6.2.jar:na]
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:542) ~[amqp-client-3.6.2.jar:na]
	... 1 common frames omitted

Who can help deal with this problem?

**Comment by acogoluegnes** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by acogoluegnes** [comment]
It's hard to tell with the amount of information provided. You can first try to upgrade to the latest Java client (4.3.0 if stuck with Java 6, 5.0.0 if you can use Java 8). Please create a new thread in the mailing.

**Comment by michaelklishin** [comment]
The stack trace says a socket read failed,

> Unrecognized Windows Sockets error: 0

is just one manifestation of it.

Network/socket operation failures is a scenario that client libraries or RabbitMQ cannot avoid. See [automatic connection recovery](http://www.rabbitmq.com/api-guide.html) in the docs. While not related, as @acogoluegnes suggested, consider using a more recent client version. RabbitMQ doesn't have to be upgraded in lock step.
