### ISSUE TITLE
get Total Message count

### ISSUE THREAD

**Issue by siedmohsen2** [rabbitmq/rabbitmq-java-client#371]
I use [this solution](https://github.com/squaremo/amqp.node/issues/207) but because my rabbitMq Server is on other server this have some delay!
That mean's when i call this url(http://username:password@queue-server:15672/api/queues/%2f/queue_name.queue) and use (messages_unacknowledged , messages_ready) this field is not null but the queue  is actually  EMPTY!!!
has any idea???

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Queues start without any stats and emit them after 5 seconds by default. Then they will be available to HTTP API clients.

We cannot suggest much with the amount of information provided.

**Comment by siedmohsen2** [comment]
asdfsdf

**Comment by michaelklishin** [comment]
This has been discussed numerous times on the Internet. See `Channel#queueDeclarePassive` and its return value (non-passive declares will work as well).

Our team does not use GitHub issues for discussions, this is 100% mailing list material.

**Comment by michaelklishin** [comment]
Java client guide now has a dedicated section that covers passive declares and [how to get the number of messages in a RabbitMQ queue](http://www.rabbitmq.com/api-guide.html#passive-declaration).

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/d/msg/rabbitmq-users/vn29czwAekM/ZrK-EHdfBAAJ).
