### ISSUE TITLE
Unable to resolve host rabbitmq when hostname, password, username are set using factory methods

### ISSUE THREAD

**Issue by SkyTreasure** [rabbitmq/rabbitmq-java-client#373]
Hi , 

If i use the below method it is working fine.
```
factory = new ConnectionFactory();
factory.setUri(uri)
```

If I use 
```
factory.setUsername(BuildConfig.rabbitMQUsername);
factory.setPassword(BuildConfig.rabbitMQPassword);
factory.setHost(BuildConfig.rabbitMQHost);
factory.setPort(Integer.parseInt(BuildConfig.rabbitMQPort));
```
then i am getting Unable to resolve host exception. Is there anything that we should. I am trying to send logs from android app using the SDK **implementation  'com.rabbitmq:amqp-client:4.1.1'**

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The exception — even though it wasn't posted, so I have to guess — is pretty clear: the client cannot resolve server's hostname. There's an [entire guide on troubleshooting connectivity](http://www.rabbitmq.com/troubleshooting-networking.html).
