### ISSUE TITLE
org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException: Failed to declare queue(s)

### ISSUE THREAD

**Issue by avinash969** [rabbitmq/rabbitmq-java-client#406]
Hi,
I created a queue with a exchange and I was able to send all messages in that queue to web socket in spring boot.

Following is my code:

 @RequestMapping(value = "hello", method = RequestMethod.GET)
    public String sayHello(@RequestParam("name") String name){
        rabbitTemplate.convertAndSend(queueName, name);
        return "Message sent to RabbitMQ: Hello from "+name;

    }

@RabbitListener(queues = "${rabbitmq.queueName}")
    public void receiveMessage(String message) throws InterruptedException {
        messagingTemplate.convertAndSend("/topic/greetings", produceMessage(message));
    }

RabbitMq Confiugaration File:

   @Value("${rabbitmq.queueName}")
    String queueName;

    @Bean
    Queue queue() {
        return new Queue(queueName, false);
    }

    @Bean
    TopicExchange exchange() {
        return new TopicExchange("spring-boot-exchange");
    }

    @Bean
    Binding binding(Queue queue, TopicExchange exchange) {
        return BindingBuilder.bind(queue).to(exchange).with(queueName);
    }

Now my doubt is how to create multiple Queues with different routing keys in spring boot and send all messages in that queues to a WebSocket.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Our team does not maintain Spring AMQP. Spring AMQP questions are best posted to StackOverflow with the `spring-amqp` tag. That's where the Spring community prefers them.
