### ISSUE TITLE
createChannel should throw an exception if channel is not available

### ISSUE THREAD

**Issue by ralfstx** [rabbitmq/rabbitmq-java-client#430]
The method `Connection::createChannel` returns `null` under certain circumstances. This is correctly stated by the method's contract even though the circumstances that can lead to "no channel available" are not further described there. It seems that this happens when some maximum count is exceeded.

I believe that returning `null` is unexpected by most users of this API. It was for me and lead to an NPE. Since the method declares an `IOException` I would expect that an IOException is also thrown when the acquisition of a new channel fails for whatever reason. Not throwing an exception provokes client code that doesn't handle this case.

RabbitMQ Version: using the docker image `rabbitmq:3-management`.

**Comment by michaelklishin** [comment]
I'm afraid I cannot agree with your reasoning about the method's contract.

Inability to allocate a channel is not an I/O exception. An I/O exception can be thrown because the operation failed on the network. We could use a different exception but returning a `null` makes sense to me. JavaDocs [state that that is a possible return value](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/Connection.java#L121).

Another factor here is that this is the API this client has had for a decade and it is not a common complaint.

**Comment by michaelklishin** [comment]
To be clear: a `null` will be returned when the [maximum number of channels allowed on a connection](https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.conf.example#L270) has been reached. Default value for the limit is [2047](https://github.com/rabbitmq/rabbitmq-server/blob/master/Makefile#L28) and it should be more than enough for just about every use case (in fact, recommended values are usually much lower).

**Comment by michaelklishin** [comment]
@ralfstx we addressed this in #430 by introducing an alternative method. Thank you for bringing this idea up.
