### ISSUE TITLE
Use URIs Connection Default Virtual Host Error 530 

### ISSUE THREAD

**Issue by aphage** [rabbitmq/rabbitmq-java-client#610]
I've set the permissions.

Virtual host | Configure regexp | Write regexp | Read regexp |  
-- | -- | -- | -- | --
/ | .* | .* | .* |  
Aphage | .* | .* | .*

Examples of my use of the official website
```
ConnectionFactory = new ConnectionFactory ();
Factory.setUri ("amqp://hello:hello@192.168.92.128:5672/");
Connection conn = factory. newConnection ();
```
Connection default Virtual Host "/" error 530
But specifying Virtal Host can
For example, "amqp://hello:hello@192.168.92.128:5672/Aphage"

There's no problem with this.
```
ConnectionFactory = new ConnectionFactory ();
// "guest"/"guest" by default, limited to localhost connections
Factory. setUsername (userName);
Factory. setPassword (password);
Factory. setVirtualHost (virtual Host);
Factory. setHost (hostName);
Factory. setPort (portNumber);
Connection conn = factory. newConnection ();
```
Is this a bug?

**Comment by Stephan202** [comment]
(Digging in my memory:) I vaguely recall being surprised by this too, long ago. IIRC the correct URL for vhost `/` is:
```
amqp://hello:hello@192.168.92.128:5672/%2F
```
(Note that while this may feel odd, it's actually correct: the vhost is `/`, after all, not the empty string.)

**Comment by aphage** [comment]
> (Digging in my memory:) I vaguely recall being surprised by this too, long ago. IIRC the correct URL for vhost `/` is:
> 
> ```
> amqp://hello:hello@192.168.92.128:5672/%2F
> ```
> 
> (Note that while this may feel odd, it's actually correct: the vhost is `/`, after all, not the empty string.)

UnknownFormatConversionException: Conversion = 'F'

**Comment by aphage** [comment]
> (Digging in my memory:) I vaguely recall being surprised by this too, long ago. IIRC the correct URL for vhost `/` is:
> 
> ```
> amqp://hello:hello@192.168.92.128:5672/%2F
> ```
> 
> (Note that while this may feel odd, it's actually correct: the vhost is `/`, after all, not the empty string.)

Thank You！

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
See [URI spec](https://www.rabbitmq.com/uri-spec.html). Slashes in URI paths must be encoded. Your URI uses vhost of `""` (an empty string).

**Comment by tengqiu** [comment]
We are running into the same problem... so it is a feature not a bug? @michaelklishin how about adding a default value '/' to vhost, if it is empty in input URI? amqp client in other language (e.g. pyamqp) works fine with a URI like "amqp://guest:guest@localhost/"

Or empty vhost is a valid virtual host in rabbitmq?

Thanks.

**Comment by lukebakken** [comment]
> Or empty vhost is a valid virtual host in rabbitmq?

No, it is not.

Please use `%2F` when referring to the `/` vhost in an AMQP URI.
