### ISSUE TITLE
com.rabbitmq.client.impl.ForgivingExceptionHandler - An unexpected connection driver error occured (Exception message: Connection reset)

### ISSUE THREAD

**Issue by arianaa30** [rabbitmq/rabbitmq-java-client#620]
I have a `RabbitMQ` client in Java listening to incoming notification messages to process them (RabbitMQ Java client version `5.5.1`). After months of running smoothly, suddenly yesterday I saw this error showing up, after which no message was received:

    [AMQP Connection 10.233.44.138:5672] WARN com.rabbitmq.client.impl.ForgivingExceptionHandler - An unexpected connection driver error occured (Exception message: Connection reset)

What is the cause of this error? How to resolve it from occuring again? Is it a bug maybe fixed in later versions?

	ConnectionFactory factory = new ConnectionFactory();
	factory.setHost(rabbitMqHost);
	factory.setUsername(rabbitMqUser);
	factory.setPassword(rabbitMqPass);
	factory.setPort(rabbitMqPort);
	factory.setVirtualHost("/");

	Connection connection = factory.newConnection();
	final Channel channel = connection.createChannel();
	channel.exchangeDeclare(EXCHANGE_NAME, "fanout");
	String queueName = channel.queueDeclare().getQueue();
	channel.queueBind(queueName, EXCHANGE_NAME, "");
	logger.info("t3- Listening to RabbitMQ notifications...");

	channel.basicConsume(queueName, false, new DefaultConsumer(channel) {
		@Override
		public void handleDelivery(String consumerTag, Envelope envelope, AMQP.BasicProperties properties,
				byte[] body) throws IOException {
			// (process the message components here ...)
			final String message = new String(body, "UTF-8");

			try {
				Thread.sleep(500);
			} catch (InterruptedException e) {
			}
					ParseStatusMessage(message);
		}
	});
}

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The message provides a line from the root cause: `Connection reset`. Given that this happened in a consumer handler, this could be any code that uses network sockets, not necessarily RabbitMQ connection.

Relevant doc guides:

 * [Network failure recovery in the Java client](https://www.rabbitmq.com/api-guide.html#recovery) (again, we have no evidence that it's the RabbitMQ connection that was closed by the peer)
 * [Automatic requeueing in manual acknowledgement mode](https://www.rabbitmq.com/confirms.html#automatic-requeueing)
 * [Data Safety topics](https://www.rabbitmq.com/reliability.html)

**Comment by michaelklishin** [comment]
[ForgivingExceptionHandler](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/ForgivingExceptionHandler.java#L24) JavaDocs explain its purpose.
