### ISSUE TITLE
Does rabbitmq-java-client support sending MQTT messages?

### ISSUE THREAD

**Issue by yueyou16** [rabbitmq/rabbitmq-java-client#628]
Does rabbitmq-java-client support sending MQTT messages? I want to use rabbitmq-java-client to send MQTT messages to rabbitmq-server. The MQTT plug-in (rabbitmq-plugins enable rabbitmq_mqtt) has been enabled in rabbitmq-server.

**Comment by acogoluegnes** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by acogoluegnes** [comment]
No, it does not, it is an AMQP 0-9-1 client. You can use a library like [Eclipse Paho](https://www.eclipse.org/paho/clients/java/) to send MQTT messages to RabbitMQ.

**Comment by yueyou16** [comment]
thank you

**Comment by yueyou16** [comment]
> 不，不是，它是AMQP 0-9-1客户端。您可以使用[Eclipse Paho之](https://www.eclipse.org/paho/clients/java/)类的库将MQTT消息发送到RabbitMQ。

thank you
