### ISSUE TITLE
Clarify License Obligations

### ISSUE THREAD

**Issue by MrMinimal** [rabbitmq/rabbitmq-java-client#630]
# Summary
As a user of rabbitmq-java-client I want to be certain what license obligations I have to obey.
Specifically it's important to clarify under which of these the project is licensed:
* MPL **_AND_** GPL **_AND_** MPL
* MPL **_OR_** GPL **_OR_** MPL

The mention that it's "triple-licensed" is not a legally binding term and can be misunderstood.

# Relevant files
* https://raw.githubusercontent.com/rabbitmq/rabbitmq-java-client/master/LICENSE

**Comment by michaelklishin** [comment]
There is a [documentation section dedicated to licensing](https://www.rabbitmq.com/api-guide.html#license). IANAL so I don't know what wording would be legally binding. Double licensing is a relatively common thing these days and it *always* means "A or B" since some licenses are inherently incompatible with each other (which is why double and triple licensing exists).
