### ISSUE TITLE
work queue - create 200 channels on one connection to create 200 consumers to consume one queue

### ISSUE THREAD

**Issue by turnhead** [rabbitmq/rabbitmq-java-client#658]
RabbitMQ version & Erlang version:
RabbitMQ 3.3.3, Erlang 17 
amqp-client: 4.0.0

I want to create 200 consumer threads to consume one queue with round-robin dispatching to improve throughput, as the code following:
`
          while (count.get() < 200) {
                
                Channel channelx = connection.createChannel();
                
                channelx.queueDeclare("work_queue_hello", false, false, false, null);
                
                int index = count.get();
                
                Consumer consumerx = new DefaultConsumer(channel){
                    @Override
                    public void handleDelivery(String consumerTag, Envelope envelope, AMQP.BasicProperties properties, byte[] body) throws IOException {
                        
                        logger.info("start run limit consumer-{}....", index);
                        
                        
                        try {
                            Thread.sleep(10*1000);
                        } catch (InterruptedException e) {
                            // TODO Auto-generated catch block
                           
                        }

                    }
                };
                
                channelx.basicConsume("work_queue_hello",autoAck,consumerx);
                count.incrementAndGet();
            }
`

I think 200 threads are running simultaneously when hundreds of messages are incoming, but I find that only eight consumer threads not 200 threads are running at the same time, please tell me why , thank you!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
