### ISSUE TITLE
QueueingConsumer alternative in 5.10.0 version

### ISSUE THREAD

**Issue by damontheimpulsive** [rabbitmq/rabbitmq-java-client#665]
I am using rabbitmq client lib 3.5.3 version. I have updated version of client lib to 5.10.0. 
After updating the version I am getting compilation issues as I am using QueueingConsumer.java in my code base.
Is there any alternative of QueueingConsumer in latest version

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There is no alternative but you can fairly trivially put your own one together. It was a `DefaultConsumer` subclass that has put all deliveries into a synchronized queue and provided a way to iterate over it. We discourage this consumer implementation approach these days as it several downsides discussed many times over the last few years. But you can still roll your own consumer implementation that works more or less that way.
