### ISSUE TITLE
Connection by URI with amqs doesn't use default ssl context

### ISSUE THREAD

**Issue by AlexisCothenet** [rabbitmq/rabbitmq-java-client#673]
Hello All

Is there any reason why, using the setUri method for connecting, with amqs protocol, the default ssl context is not used ?
Here is the relative code : [here](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/ConnectionFactory.java#L312)

_useSslProtocol()_ is called and it calls another method that calls _TrustEverythingTrustManager_.
Could we call the `useSslProtocol(SSLContext.getDefault());` method instead according to you ?

**Comment by acogoluegnes** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by acogoluegnes** [comment]
Using the default `SSLContext` would mean using the default trust manager, which implies trusting only brokers whose certificate is in there. Most first attempts to connect using TLS (usually during development) would then fail, which is likely to result in questions on the mailing list.

Using by default a trust manager that trusts all brokers and emits a warning with a link to the documentation is a compromise we settled on a few years, see #229 for history.
