### ISSUE TITLE
Allow maintaining of address order with auto recovery

### ISSUE THREAD

**Issue by ValSmith** [rabbitmq/rabbitmq-java-client#689]
According to the documentation you can use an AddressResolver to choose a desired host first. I created a resolver that returns [host1,host2,host3] but then found that the connections were all to host2 even though host 1 was available. After a while I discovered that when autoRecovery=true the address list is always shuffled. Could there be a possibility to maintain the list order when using auto recovery? Or is there a very intentional reason this is not allowed?

**Comment by michaelklishin** [comment]
This is by design. 

Depending on the order of endpoints doesn't sound like a good idea. Any client can [connect to any cluster node](https://www.rabbitmq.com/clustering.html#clustering-and-clients). If a "preferred" node is unreachable, attempts to connect to it sequentially will simply increase the amount of time it takes to reach to a reachable endpoint with a "lower priority".
