### ISSUE TITLE
Add JMX monitoring

### ISSUE THREAD

**Issue by augi** [rabbitmq/rabbitmq-java-client#79]
It would be very useful to get at least some basic statistics published via JMX. E.g. number of messages published, consumed, rejected, number of threads used etc.

**Comment by michaelklishin** [comment]
This is a good idea but there's one problem: this means we'd have an external dependency on something like the Metrics library. Historically the client has been trying hard to stay dependency-free as much as possible.

Besides that, what specific metrics do you want to collect? Number of threads used by the library is not necessarily easy to calculate because custom thread executors and factories can be provided.

Per protocol method stats (number of messages published, delivered, acked, nacked, fetched with basic.get) sounds good.

**Comment by stevecstian** [comment]
How about optional dependency?

**Comment by michaelklishin** [comment]
If the dependency is optional then the feature is also opt-in. This may be a decent middle ground.

**Comment by Augi** [comment]
I don't have deep understanding of the Client internals so I picked few metric that could be interesting (mainly number of messages).

If we don't want to add more dependencies to Client then we could introduce a plain `interface` for metrics, support it in `ConnectionFactory`, and call it from the right places. The implementation could be in separate project then.

Optional dependency could be also viable solution.

**Comment by michaelklishin** [comment]
@Augi yes, that sounds reasonable.

**Comment by MartinGoodwell** [comment]
Is there any progress on JMX integration?
I wanted to add that for pure JMX metrics, no additional dependency is required as any functionality is available in the `javax.management` package.
Here's an example (where `BrokerMetrics` is a POJO that implements an interface called `BrokerMetricsMBean`:
```
//Get the MBean server
MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
//register the MBean
BrokerMetrics mBean = new BrokerMetrics();
ObjectName name = new ObjectName("com.rabbitmq:type=Broker");
mbs.registerMBean(mBean, name);
```
Here's a more verbose example (with quite some annoying ads): http://www.journaldev.com/1352/what-is-jmx-mbean-jconsole-tutorial

I tried to do the implementation myself but I already failed at building the rabbitmq-java-client (error in antrun)
